[package]
name = "hitt-cli"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.75"
crossterm = { version = "0.27.0", features = ["event-stream"] }
hitt-parser = { path = "../hitt-parser" }
reqwest = "0.11.20"
serde = "1.0.188"
tokio = { version = "1.32.0", features = ["full"] }
