[package]
name = "hitt"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true

[[bin]]
name = "hitt"
path = "src/main.rs"

[dependencies]
clap = { version = "4.3.24", features = ["derive"] }
console = "0.15.7"
ignore = "0.4.20"
hitt-formatter = { path = "../hitt-formatter" }
hitt-parser = { path = "../hitt-parser" }
hitt-request = { path = "../hitt-request" }
shell-words = "1.1.0"
tempfile = "3.8.1"
tokio = { version = "1.32.0", features = ["fs", "macros", "rt-multi-thread"] }
