[package]
name = "hitt"
description.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
categories.workspace = true
rust-version = "1.74"

[[bin]]
name = "hitt"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.6", features = ["derive"] }
clap_complete = { version = "4.5.5" }
crossterm = "0.27.0"
futures = { workspace = true }
hitt-formatter = { workspace = true }
hitt-parser = { workspace = true }
hitt-request = { workspace = true }
hitt-sse = { workspace = true }
http = { workspace = true }
ignore = { version = "0.4.22" }
reqwest = { workspace = true }
shell-words = { version = "1.1.0" }
tempfile = { version = "3.10.1" }
tokio = { workspace = true }
