[package]
name = "hitt-cli"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "hitt"
path = "src/main.rs"

[dependencies]
clap = { version = "4.3.24", features = ["derive"] }
hitt-parser = { path = "../hitt-parser" }
hitt-request = { path = "../hitt-request" }
jsonformat = "2.0.0"
reqwest = "0.11.20"
tokio = { version = "1.32.0", features = ["full"] }
