[package]
name = "hitt"
description.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
categories.workspace = true

[[bin]]
name = "hitt"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.16", features = ["derive"] }
console = { version = "0.15.8" }
hitt-formatter = { workspace = true }
hitt-parser = { workspace = true }
hitt-request = { workspace = true }
http = { workspace = true }
ignore = { version = "0.4.22" }
reqwest = { workspace = true }
shell-words = { version = "1.1.0" }
tempfile = { version = "3.9.0" }
tokio = { workspace = true }
