[package]
name = "hitt-parser"
description = "Parser for http files for the hitt http testing tool"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
rust-version.workspace = true
homepage.workspace = true

[dependencies]
http = { workspace = true }
