[package]
name = "hitt-formatter"
description = "Code formatter for the hitt http testing tool"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
rust-version.workspace = true
homepage.workspace = true
readme = "README.md"
categories = []

[dependencies]
jsonformat = "2.0.0"
