[package]
name = "hitt-request"
description = ""
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
rust-version.workspace = true
homepage.workspace = true

[dependencies]
hitt-parser = { path = "../hitt-parser" }
reqwest = "0.11.23"
tokio = { version = "1.32.0" }
