[package]
name = "hitt-request"
version = "0.0.1"
edition = "2021"

[dependencies]
hitt-parser = { path = "../hitt-parser" }
reqwest = "0.11.20"
serde = "1.0.188"
tokio = { version = "1.32.0", features = ["full"] }
