name: coverage
on: [push]
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --all-targets --workspace --locked --codecov --output-path codecov.json
      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          files: codecov.json
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: hougesen/hitt
