name: release
on:
  push:
    tags: ['*']
  workflow_dispatch:
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
  release_cargo:
    name: Publish to cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Publish hitt-formatter
        run: cargo publish -p hitt-formatter  --verbose --locked --token ${{ secrets.CARGO_TOKEN }}
      - name: Publish hitt-parser
        run: cargo publish -p hitt-parser  --verbose --locked --token ${{ secrets.CARGO_TOKEN }}
      - name: Publish hitt-request
        run: cargo publish -p hitt-request  --verbose --locked --token ${{ secrets.CARGO_TOKEN }}
      - name: Publish hitt
        run: cargo publish -p hitt  --verbose --locked --token ${{ secrets.CARGO_TOKEN }}
